# -*- coding: utf-8 -*-
"""
tpematsfactory.com data layer - generated by tools/emit_site_data.py.

Source: the product catalogue of https://lywalter.en.alibaba.com (Linyi Walt),
scraped 2026-09-20. Product titles, prices and MOQ come from the listings.

FITMENT PROVENANCE - read this before trusting the vehicle index:
  * make/model come from the listing TITLE, which is product-specific.
  * The detail pages' structured "Car Fitment" / Model / Year attributes were
    NOT used: they are shop-wide boilerplate (86 of 96 listings carried the
    same signature), so importing them would have put "fits Ford Ranger" on an
    unrelated listing.
  * Years are only present for the few listings that state them. Everything
    else is deliberately blank - confirm against the mould list, never guess.

Trading entity on the site: Linyi Strawberry International Trade Co., Ltd.
"""

SITE = {
    "brand": "TPE Mats Factory",
    "short": "TMF",
    "domain": "tpematsfactory.com",
    "tagline": "3D TPE Car Floor Liners Direct from the Factory",
    "whatsapp": "8618669693290",

    # Must be created for THIS site - the generator skips anything blank, so no
    # placeholder id is ever published.
    "email": "",
    "formspree": "",
    "ga4": "",
    "clarity": "",

    "bank_beneficiary": "Linyi Strawberry International Trade Co., Ltd",
    "bank_account": "63003927994",
    "bank_swift": "CHASHKHH / CHASHKHHXXX",
    "bank_note": "USD Payments: Recommend using US J.P. Morgan (CHASUS33) as transit bank "
                 "to reduce forex risk. This account cannot receive payments from Russia and Belarus.",

    # Only real certificates - empty means the trust block stays hidden.
    "certificates": [],
}

CATEGORIES = [
    {"id": "floor-liners", "name": "3D TPE Floor Liners", "nav": "Floor Liners",
     "blurb": "Laser-measured 3D full-coverage liners with high side walls and OE fixing points."},
    {"id": "all-weather-mats", "name": "All-Weather Floor Mats", "nav": "All-Weather",
     "blurb": "Flat and semi-universal TPE mats for year-round protection against mud, snow and spills."},
    {"id": "trunk-mats", "name": "Trunk Mats & Cargo Liners", "nav": "Trunk Mats",
     "blurb": "Boot and cargo-area liners cut to the load floor, with raised edges."},
    {"id": "double-layer-mats", "name": "Double-Layer Mats", "nav": "Double Layer",
     "blurb": "Detachable two-layer construction: lift the top layer out, hose the base."},
]

# ---------------------------------------------------------------------------
# PRODUCTS (51)
# ---------------------------------------------------------------------------
PRODUCTS = [
 {
  "slug": "audi-a6-a8-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Audi A6 A8",
  "badge": "3D Fit",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/audi-a6-a8-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Premium-Custom-Mold-3D-5D-TPE_1601873110913.html",
  "fitment": {
   "make": "Audi",
   "model": "A6 A8",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Floor liner for the Audi A6 and A8, made as a moulded 3D and 5D tray with a deep channel running the length of each footwell. That channel is there to trap meltwater, snow and mud below the level of the surrounding trim, which is useful where winters are wet. Three pieces cover the front and rear rows. The TPE compound is odourless, plasticiser-free, halogen-free and recyclable, and it does not harden in cold weather. Lifting the liner out and rinsing it is enough to clear the channel for the next season. Model year is not fixed in this listing, so confirm it at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Audi A6 A8 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Audi A6 a8"
   ]
  ],
  "points": [
   "Deep channel traps meltwater, snow and mud",
   "Moulded for the Audi A6 and A8 footwells",
   "Plasticiser-free TPE stays soft in cold",
   "Confirm model year at order stage"
  ],
  "related": [
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners",
   "buick-excelle-floor-liners"
  ]
 },
 {
  "slug": "byd-atto-all-weather-mats",
  "cat": "all-weather-mats",
  "name": "All-Weather TPE Floor Mats for BYD Atto",
  "badge": "Custom Fit",
  "price": "$18-20/set",
  "moq": "MOQ 10 sets",
  "img": "/images/byd-atto-all-weather-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/Eco-Odorless-3D-TPE-Floor-Liners_1601876893773.html",
  "fitment": {
   "make": "BYD",
   "model": "Atto",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "All-season mats moulded for the BYD Atto in left-hand drive, supplied as a three-piece set for the driver, passenger and rear footwells. The surface is flat enough to sit underfoot without catching, while the raised perimeter and ribbed pattern hold water, sand and road salt that comes in on shoes. TPE is odourless, carries no plasticiser, stays pliable in cold, and is halogen-free and recyclable. Mud dries and lifts off, so cleaning takes a moment with a brush and hose. Produced in left-hand-drive tooling only, so buyers should confirm the drive side. Ten sets minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "BYD Atto - confirm year with us"
   ],
   [
    "Coverage",
    "All-season flat mat, raised perimeter"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W BYD"
   ]
  ],
  "points": [
   "Left-hand-drive tooling, three-piece set",
   "Ribbed surface channels water and road salt",
   "Odourless TPE without plasticiser",
   "Ten-set minimum suits distributor stocking"
  ],
  "related": [
   "byd-dolphin-seal-atto3-all-weather-mats",
   "byd-song-plus-dm-i-seal-all-weather-mats",
   "chevrolet-all-weather-mats"
  ]
 },
 {
  "slug": "byd-dolphin-seal-atto3-all-weather-mats",
  "cat": "all-weather-mats",
  "name": "All-Weather TPE Floor Mats for BYD Dolphin Seal Atto3",
  "badge": "All-Season",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/byd-dolphin-seal-atto3-all-weather-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-3D-TPE-Car-Floor-Mats_1601867428314.html",
  "fitment": {
   "make": "BYD",
   "model": "Dolphin Seal Atto3",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "All-weather TPE set moulded for the BYD Dolphin, Seal and Atto 3 in left-hand drive, supplied as a full three-piece set. The mats give all-season protection with a waterproof surface and an anti-slip backing that keeps them steady underfoot. TPE is odourless and plasticiser-free, halogen-free and recyclable, and does not stiffen in cold weather. Mud, salt and drink spillage lift off with a rinse, so the set returns to service quickly. The three mats cover the driver footwell, the front passenger side and the rear row. Confirm your model, drive side and year at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "BYD Dolphin Seal Atto3 - confirm year with us"
   ],
   [
    "Coverage",
    "All-season flat mat, raised perimeter"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "BYD Dolphin"
   ]
  ],
  "points": [
   "Left-hand-drive set for Dolphin, Seal and Atto 3",
   "Anti-slip backing holds mats steady",
   "Waterproof and odourless TPE",
   "Confirm model, drive side and year"
  ],
  "related": [
   "byd-atto-all-weather-mats",
   "byd-song-plus-dm-i-seal-all-weather-mats",
   "chevrolet-all-weather-mats"
  ]
 },
 {
  "slug": "byd-seagull-atto-1-ev-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for BYD Seagull Atto 1 EV",
  "badge": "Low MOQ",
  "price": "$18-20/set",
  "moq": "MOQ 10 sets",
  "img": "/images/byd-seagull-atto-1-ev-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-5D-Full-Coverage-TPE-Mats_1601874912130.html",
  "fitment": {
   "make": "BYD",
   "model": "Seagull Atto 1 EV",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Five-dimensional full-coverage liner moulded for the BYD Seagull and Atto 1 EV, with a deep channel and raised walls that trap mud and spills inside the tray. The moulded edges wrap the footwell rather than stopping at the carpet edge, so grit stays off the trim. Three pieces cover the front and rear. TPE is odourless and plasticiser-free, stays flexible in cold, and is halogen-free and recyclable; the surface is waterproof and easy to rinse. Buyers should confirm model and year at order stage. Ten sets minimum, which suits a distributor stocking a popular electric model. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "BYD Seagull Atto 1 EV - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "TPE Car Mats"
   ]
  ],
  "points": [
   "Moulded for BYD Seagull and Atto 1 EV",
   "Deep channel traps mud and spills",
   "Moulded tray edges protect the trim",
   "Ten-set minimum suits EV-focused distributors"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "buick-floor-liners",
   "buick-excelle-floor-liners"
  ]
 },
 {
  "slug": "byd-song-plus-dm-i-seal-all-weather-mats",
  "cat": "all-weather-mats",
  "name": "All-Weather TPE Floor Mats for BYD Song Plus DM-i Seal",
  "badge": "OEM Ready",
  "price": "$17-19/set",
  "moq": "MOQ 1 set",
  "img": "/images/byd-song-plus-dm-i-seal-all-weather-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-All-Weather-TPE-Car-Floor_1601879010206.html",
  "fitment": {
   "make": "BYD",
   "model": "Song Plus DM-i Seal",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "All-weather floor liner moulded for the BYD Song Plus DM-i and Seal in left-hand drive, giving full coverage of the footwell with a waterproof, anti-slip surface. The mat is odourless because the TPE contains no plasticiser, and it is halogen-free and recyclable, staying flexible in cold weather. Water, mud and drink spills sit on the surface and lift off with a rinse, which keeps the cabin presentable through a wet season. Three pieces cover the front and rear. Confirm the model, drive side and year when ordering. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "BYD Song Plus DM-i Seal - confirm year with us"
   ],
   [
    "Coverage",
    "All-season flat mat, raised perimeter"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "BYD Song Plus DM-i"
   ]
  ],
  "points": [
   "Left-hand-drive set for Song Plus DM-i and Seal",
   "Waterproof, anti-slip full coverage",
   "Odourless TPE without plasticiser",
   "Confirm model, drive side and year"
  ],
  "related": [
   "byd-atto-all-weather-mats",
   "byd-dolphin-seal-atto3-all-weather-mats",
   "chevrolet-all-weather-mats"
  ]
 },
 {
  "slug": "buick-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Buick - Made to Order",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/buick-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Fit-3D-TPE-Car-Floor_1601880868782.html",
  "fitment": {},
  "desc": "Full-coverage TPE floor liner built as a three-dimensional tray with high side walls and a deep channel that holds slush, grit and spilled drinks away from the carpet. Made to order for your Buick model, so the moulding follows the footwell rather than sitting flat on top of it. Sets are supplied in 3-piece and 5-piece configurations. The TPE compound is odourless because it carries no plasticiser, stays flexible in cold weather, and is halogen-free and recyclable. Water does not soak in, so a rinse and a wipe is usually enough to bring the liner back. Confirm your model and year when ordering. FOB pricing on request, with one set as the minimum order.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Buick - model and year on request"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Leather Car Mats"
   ]
  ],
  "points": [
   "Moulded tray holds slush and grit off the carpet",
   "Odourless TPE with no plasticiser",
   "3pc and 5pc sets to match coverage",
   "One set minimum for trial orders"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-excelle-floor-liners"
  ]
 },
 {
  "slug": "buick-trunk-mats",
  "cat": "trunk-mats",
  "name": "TPE Cargo Liner for Buick - Made to Order",
  "badge": "Custom Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/buick-trunk-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-TPE-car-floor-mats-cargo_1601881068235.html",
  "fitment": {},
  "desc": "Cargo-area liner in TPE, cut as a moulded tray for the boot floor of your Buick model, with raised edges that contain wet kit, soil or loose shopping before it soils the trim. Because the fitment is made to order, we ask for your model and year before tooling the run. The material is odourless, free of plasticiser, halogen-free and recyclable, and it keeps its flexibility when the temperature drops. A single-piece liner is quick to lift out and hose down. Supplied at one set minimum so buyers can check the pattern before committing to a full programme. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Buick - model and year on request"
   ],
   [
    "Coverage",
    "Cargo-area coverage, raised lip"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Leather Car Mats"
   ]
  ],
  "points": [
   "Cargo tray shaped for your Buick boot floor",
   "Raised edges contain wet or dirty loads",
   "Odourless, halogen-free, recyclable TPE",
   "One set minimum for pattern approval"
  ],
  "related": [
   "hyundai-elantra-sedan-3-5mm-trunk-mats",
   "tesla-cybertruck-trunk-mats"
  ]
 },
 {
  "slug": "buick-excelle-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Buick Excelle",
  "badge": "All-Season",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/buick-excelle-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/TPE-3D-5D-car-floor-mats_1601870374265.html",
  "fitment": {
   "make": "Buick",
   "model": "Excelle",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Custom-fit TPE floor liner for the Buick Excelle, moulded to the footwell shape rather than trimmed to a generic outline, so the edges meet the trim and the carpet stays covered. The liner is waterproof and the surface is easy to clean with a rinse or a wipe. Three pieces cover the front and rear footwells. TPE carries no plasticiser, which keeps the set odourless, and it is halogen-free, recyclable and flexible in cold weather. Buyers should confirm the model and year at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Buick Excelle - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Buick Excelle"
   ]
  ],
  "points": [
   "Custom fit moulded for the Buick Excelle",
   "Moulded edges meet the interior trim",
   "Waterproof TPE wipes clean",
   "Single-set minimum for evaluation"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "changan-cs75-plus-mk4-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Changan CS75 PLUS MK4",
  "badge": "Low MOQ",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/changan-cs75-plus-mk4-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Injection-Molding-Deep-Dish-Car_1601867094594.html",
  "fitment": {
   "make": "Changan",
   "model": "CS75 PLUS MK4",
   "years": "",
   "body": "Suv",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Deep dish floor liner moulded specifically for the Changan CS75 PLUS MK4 SUV in left-hand drive, using injection moulding to hold the footwell contour. The tray walls are raised and the dish is deep enough to hold water and grit brought in on wet boots. Three pieces cover the front and rear. TPE is odourless and plasticiser-free, halogen-free and recyclable, and stays flexible in low temperatures. Cleaning is a lift-out and a rinse. Confirm the model and year when placing the order so the tooling matches. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Changan CS75 PLUS MK4 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "Body type",
    "Suv"
   ],
   [
    "MOQ",
    "1 set"
   ]
  ],
  "points": [
   "Injection-moulded for Changan CS75 PLUS MK4 SUV",
   "Deep dish holds water and grit",
   "Left-hand-drive tooling",
   "Confirm model and year before tooling"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "changan-uni-t-2023-2026-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Changan UNI-T 2023-2026 2023-2026",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/changan-uni-t-2023-2026-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-TPE-Car-Floor-Mats-LHD_1601926685587.html",
  "fitment": {
   "make": "Changan",
   "model": "UNI-T 2023-2026",
   "years": "2023-2026",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Custom-fit floor liner moulded for the Changan UNI-T over 2023-2026, left-hand drive, and produced on the W281 tool. The 3D tray wraps the footwell with high side walls so water, snow and grit stay inside the liner; the surface is waterproof and the backing is anti-slip. TPE has no plasticiser, so the set has no plastic smell, and it stays flexible in cold, is halogen-free and recyclable. Confirmation of model and year at order stage keeps the pattern correct. One set minimum makes it easy to test the fit. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Changan UNI-T 2023-2026 (2023-2026)"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W281 CHANGAN"
   ]
  ],
  "points": [
   "Moulded for the UNI-T 2023-2026, left-hand drive",
   "High side walls retain water and grit",
   "Anti-slip backing keeps the tray steady",
   "Single-set minimum for fitment testing"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "chery-fulwin-t9l-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Chery Fulwin T9L",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/chery-fulwin-t9l-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-TPE-Floor-Liner-Mats-for_1601927874369.html",
  "fitment": {
   "make": "Chery",
   "model": "Fulwin T9L",
   "years": "",
   "body": "Suv",
   "hand": "",
   "positions": []
  },
  "desc": "TPE floor liner moulded for the Chery Fulwin T9L SUV, built as a tray with high side walls that follow the footwell and raise the containment line above the carpet. Water, dust and grit stay inside the liner, which is what an SUV used on mixed roads needs. Three or five pieces cover the rows. The compound is odourless, carries no plasticiser, is halogen-free and recyclable, and keeps its flexibility in cold weather. A rinse and a wipe is enough to clean it. Confirm the model and year before ordering. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Chery Fulwin T9L - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Body type",
    "Suv"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W CHERY"
   ]
  ],
  "points": [
   "Moulded for the Chery Fulwin T9L SUV",
   "High side walls contain dust and water",
   "Flexible, odourless, recyclable TPE",
   "Single-set minimum to test the fit"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "chery-tiggo-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Chery Tiggo",
  "badge": "Custom Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/chery-tiggo-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/TPE-Car-Floor-Liners-for-Chery_1601946505793.html",
  "fitment": {
   "make": "Chery",
   "model": "Tiggo",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "TPE floor liner moulded for the Chery Tiggo range, built as a 3D tray with high side walls that follow the footwell and the edge of the sill. The shape stops water and grit migrating under the pedals or into the carpet edge. Sets come in three or five pieces depending on the row coverage required. TPE carries no plasticiser, so there is no plastic odour, and it remains flexible in cold conditions, is halogen-free and recyclable. The surface is waterproof, so a rinse and a cloth deals with most marks. Buyers should confirm the exact Tiggo variant and year. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Chery Tiggo - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Chery Tiggo 7"
   ]
  ],
  "points": [
   "Moulded for the Chery Tiggo range",
   "Sets supplied in three or five pieces",
   "Waterproof, odourless TPE wipes clean",
   "Confirm Tiggo variant and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "chevrolet-all-weather-mats",
  "cat": "all-weather-mats",
  "name": "All-Weather TPE Floor Mats for Chevrolet - Made to Order",
  "badge": "All-Season",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/chevrolet-all-weather-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-Direct-3D-Molded-TPE-Floor_1601869291791.html",
  "fitment": {},
  "desc": "All-weather TPE floor mat set made to order for your Chevrolet model, moulded as a 3D liner with an anti-slip underside. The surface is waterproof and easy to wash, so salt, mud and spilled drinks wipe away without soaking into the carpet. Sets are supplied in three pieces. TPE uses no plasticiser, so there is no plastic odour, and it is halogen-free, recyclable and stays soft in cold weather. Because fitment is produced to order, buyers should send the model and year with the enquiry. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Chevrolet - model and year on request"
   ],
   [
    "Coverage",
    "All-season flat mat, raised perimeter"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Leather Car Mats"
   ]
  ],
  "points": [
   "Made to order for your Chevrolet model",
   "Anti-slip underside holds the mat steady",
   "Washable waterproof TPE surface",
   "Three-piece set for front and rear"
  ],
  "related": [
   "byd-atto-all-weather-mats",
   "byd-dolphin-seal-atto3-all-weather-mats",
   "byd-song-plus-dm-i-seal-all-weather-mats"
  ]
 },
 {
  "slug": "fiat-palio-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Fiat Palio",
  "badge": "Low MOQ",
  "price": "$16-18/set",
  "moq": "MOQ 10 sets",
  "img": "/images/fiat-palio-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-Custom-TPE-Car-Floor-Mat_1601881440166.html",
  "fitment": {
   "make": "Fiat",
   "model": "Palio",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Left-hand-drive floor liner moulded for the Fiat Palio on tool W-02, with a 3D tray profile and high side walls suited to dusty roads and wet seasons. Sets are supplied in three or five pieces. TPE is odourless with no plasticiser, halogen-free and recyclable, and stays pliable when the temperature drops, so the liner is easy to empty and refit. Waterproof construction means a rinse is normally enough. Because the drive side is fixed in the tooling, buyers should confirm left-hand drive and model year before ordering. Ten sets minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Fiat Palio - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W-02 FAIT"
   ]
  ],
  "points": [
   "Left-hand-drive tooling W-02 for Fiat Palio",
   "3pc and 5pc set options",
   "Odourless TPE, halogen-free, recyclable",
   "Ten-set minimum suits first container order"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "ford-f150-raptor-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Ford F150 Raptor",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/ford-f150-raptor-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-TPE-Floor-Liner-Mats-for_1601927684689.html",
  "fitment": {
   "make": "Ford",
   "model": "F150 Raptor",
   "years": "",
   "body": "Pickup",
   "hand": "",
   "positions": []
  },
  "desc": "Floor liner built for the Ford F150 Raptor and shaped as a 3D tray rather than a flat mat, with raised edges that suit a pickup used on site or in the field. The moulding follows the footwell contours so the liner sits low and does not bunch under the pedals. TPE resists water, is odourless without plasticiser, halogen-free and recyclable, and stays soft when temperatures fall. Cleaning is straightforward: lift the liner out, tip the debris and rinse. As the year is not fixed in this listing, buyers should confirm their model year when ordering. Minimum order is one set and FOB pricing is available on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Ford F150 Raptor - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Body type",
    "Pickup"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W FORD"
   ]
  ],
  "points": [
   "Tray form moulded for the F150 Raptor pickup",
   "Contoured to sit flat in the footwell",
   "Waterproof TPE, no plasticiser odour",
   "Confirm model year when ordering"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "ford-ranger-escape-mustang-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Ford Ranger Escape Mustang",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/ford-ranger-escape-mustang-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-5D-Molded-TPE-Foot-Mats_1601876669853.html",
  "fitment": {
   "make": "Ford",
   "model": "Ranger Escape Mustang",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Five-dimensional moulded TPE mat for the Ford Ranger, Escape and Mustang, with a raised edge around the tray that keeps water and road grit on the liner. The moulding sits close to the footwell walls, which is where flat mats tend to leave gaps. Three pieces cover the front and rear footwells. The compound is odourless, contains no plasticiser, is halogen-free and recyclable, and holds its flexibility in cold weather. Cleaning is a quick lift-out, tip and rinse. Confirm which model and which year the order is for. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Ford Ranger Escape Mustang - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Ford Ranger"
   ]
  ],
  "points": [
   "Raised edge keeps grit on the liner",
   "Moulded for Ford Ranger, Escape and Mustang",
   "Flexible in cold, halogen-free TPE",
   "Confirm model and year for tooling"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "ford-ranger-raptor-all-weather-mats",
  "cat": "all-weather-mats",
  "name": "All-Weather TPE Floor Mats for Ford Ranger Raptor",
  "badge": "Custom Fit",
  "price": "$14-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/ford-ranger-raptor-all-weather-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/LHD-All-Weather-TPE-Floor-Liners_1601878996548.html",
  "fitment": {
   "make": "Ford",
   "model": "Ranger Raptor",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "All-weather floor mat set moulded for the Ford Ranger Raptor in left-hand drive, supplied as three pieces. The mat sits flat in the footwell with a shallow raised rim, so it works as everyday all-season protection rather than a deep tray. Wear-resistant TPE holds up under work boots, and the backing keeps the mat from sliding on the carpet. The compound is odourless, without plasticiser, halogen-free and recyclable, and it does not go stiff in cold weather. Cleaning is quick: shake it out or rinse it. Confirm the drive side and model year at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Ford Ranger Raptor - confirm year with us"
   ],
   [
    "Coverage",
    "All-season flat mat, raised perimeter"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "TPE  Car Mats"
   ]
  ],
  "points": [
   "Left-hand-drive set moulded for Ranger Raptor",
   "Flat mat profile for all-season use",
   "Wear-resistant TPE under work boots",
   "Single-set minimum to test demand"
  ],
  "related": [
   "byd-atto-all-weather-mats",
   "byd-dolphin-seal-atto3-all-weather-mats",
   "byd-song-plus-dm-i-seal-all-weather-mats"
  ]
 },
 {
  "slug": "ford-territory-destroyer-2019-2023-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Ford Territory Destroyer 2019-2023 2019-2023",
  "badge": "All-Season",
  "price": "$18-20/set",
  "moq": "MOQ 10 sets",
  "img": "/images/ford-territory-destroyer-2019-2023-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Single-Layer-5D-TPE-Car-Floor_1601920600366.html",
  "fitment": {
   "make": "Ford",
   "model": "Territory Destroyer 2019-2023",
   "years": "2019-2023",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Single-layer five-dimensional TPE liner moulded for the Ford Territory Destroyer over 2019-2023, with a waterproof, non-slip surface and raised moulded walls around the footwell. The single-layer build keeps the tray light and simple to lift out for cleaning, which suits high-mileage fleet use. Sets are supplied in three or five pieces. TPE is odourless, plasticiser-free, halogen-free and recyclable, and keeps its flexibility in cold weather. TPE does not absorb water, so the liner dries quickly after a rinse. Ten sets minimum, which fits a distributor order for a single model year band. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Ford Territory Destroyer 2019-2023 (2019-2023)"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W320 FORD"
   ]
  ],
  "points": [
   "Single-layer 5D liner for Territory Destroyer 2019-2023",
   "Waterproof, non-slip and light to lift out",
   "Three-piece or five-piece sets",
   "Ten-set minimum for single-year band orders"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "geely-ex2-xingyuan-ev-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Geely EX2 Xingyuan EV",
  "badge": "Low MOQ",
  "price": "$16-18/set",
  "moq": "MOQ 10 sets",
  "img": "/images/geely-ex2-xingyuan-ev-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-TPE-Floor-Liner-Mats-for_1601927776970.html",
  "fitment": {
   "make": "Geely",
   "model": "EX2 Xingyuan EV",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "TPE floor liner moulded for the Geely EX2 Xingyuan EV on tool W-273, following the footwell of the electric model rather than using a trimmed outline. The tray has raised sides and a deep channel that hold water, dust and grit inside the liner. Sets are supplied in three or five pieces. The compound is odourless, without plasticiser, and is halogen-free and recyclable; it stays flexible in cold weather and the surface is waterproof, so a rinse is enough. Ten sets minimum, which suits a distributor stocking an EV range. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Geely EX2 Xingyuan EV - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W-273 GEELY"
   ]
  ],
  "points": [
   "Moulded on tool W-273 for EX2 Xingyuan EV",
   "Raised sides and deep channel contain grit",
   "Waterproof and odourless TPE",
   "Ten-set minimum for EV stock programmes"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "geely-panda-mini-ev-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Geely Panda Mini EV",
  "badge": "OEM Ready",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/geely-panda-mini-ev-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-3D-5D-Molded-TPE-Car_1601865534277.html",
  "fitment": {
   "make": "Geely",
   "model": "Panda Mini EV",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Three-dimensional and five-dimensional moulded liner for the Geely Panda Mini EV, with a deep channel that captures water, dust and spills in the compact footwell. The liner is shaped for the small cabin, where a generic mat rarely sits correctly. Three pieces cover the front and rear. TPE is odourless, uses no plasticiser, stays flexible in the cold, and is halogen-free and recyclable. The waterproof surface means cleaning is a rinse rather than a scrub. Model and year should be confirmed before the order is tooled. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Geely Panda Mini EV - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Geely Panda Mini EV"
   ]
  ],
  "points": [
   "Moulded for the Geely Panda Mini EV cabin",
   "Deep channel captures dust and spills",
   "Odourless, flexible, recyclable TPE",
   "Confirm model and year before tooling"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "geely-xingyuan-ex2-ev-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Geely Xingyuan EX2 EV",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/geely-xingyuan-ex2-ev-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Fit-TPE-Floor-Mats-for_1601927876502.html",
  "fitment": {
   "make": "Geely",
   "model": "Xingyuan EX2 EV",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Custom-fit floor liner for the Geely Xingyuan EX2 EV, moulded on tool W-273 to follow the footwell shape of the electric model. High side walls and a deep channel keep water, grit and spilled drinks inside the liner, and the backing holds it against the carpet. The TPE shell is odourless, free of plasticiser, halogen-free and recyclable, and remains flexible in cold weather. Waterproof construction means the liner can be lifted out and rinsed rather than scrubbed. Buyers should confirm model and year, as this listing does not fix a production range. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Geely Xingyuan EX2 EV - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W-273 GEELY"
   ]
  ],
  "points": [
   "Moulded on tool W-273 for Xingyuan EX2 EV",
   "Deep channel holds spills and road grit",
   "Flexible, odourless, recyclable TPE",
   "Anti-slip backing resists shifting underfoot"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "honda-cr-v-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Honda CR-V",
  "badge": "Custom Fit",
  "price": "$14-18/set",
  "moq": "MOQ 1 set",
  "img": "/images/honda-cr-v-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-5D-TPE-Car-Floor-Mats_1601893469769.html",
  "fitment": {
   "make": "Honda",
   "model": "CR-V",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Full-coverage TPE floor liner moulded for the Honda CR-V in left-hand drive, supplied as a five-piece set covering the front, rear and centre footwell areas. The surface is waterproof and non-slip, and the moulded tray holds water and road grit away from the carpet. TPE is odourless because it uses no plasticiser, is halogen-free and recyclable, and keeps its flexibility in cold weather. Cleaning is a lift-out and a rinse. Buyers should confirm the model year, as the listing does not fix a production range. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Honda CR-V - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Honda CR-V"
   ]
  ],
  "points": [
   "Five-piece full-coverage set for Honda CR-V",
   "Left-hand-drive tooling",
   "Waterproof and non-slip surface",
   "Confirm model year when ordering"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "hongqi-h5-h6-h7-h9-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Hongqi H5 / H6 / H7 / H9",
  "badge": "All-Season",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/hongqi-h5-h6-h7-h9-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-5D-TPE-Car-Floor-Mats_1601887532368.html",
  "fitment": {
   "make": "Hongqi",
   "model": "H5 / H6 / H7 / H9",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Full-surround TPE liner moulded for the Hongqi H5, H6, H7 and H9, covering the footwell floor and the lower trim with raised moulded walls. Sets are supplied in three or five pieces depending on the coverage required. The TPE shell is odourless, free of plasticiser, halogen-free and recyclable, and stays flexible in cold weather, so it can be lifted out and emptied without cracking. Waterproof construction means a rinse clears most dirt. Buyers should confirm the exact variant and model year, since the listing covers several models. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Hongqi H5 / H6 / H7 / H9 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Hongqi H5"
   ]
  ],
  "points": [
   "Full-surround liner for Hongqi H5 to H9",
   "Three-piece or five-piece sets",
   "Odourless TPE lifts out without cracking",
   "Confirm variant and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "hyundai-elantra-sedan-3-5mm-trunk-mats",
  "cat": "trunk-mats",
  "name": "TPE Cargo Liner for Hyundai Elantra Sedan 3.5mm",
  "badge": "Low MOQ",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/hyundai-elantra-sedan-3-5mm-trunk-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-TPE-Rubber-Full-Set-Car_1601889210437.html",
  "fitment": {
   "make": "Hyundai",
   "model": "Elantra Sedan 3.5mm",
   "years": "",
   "body": "Sedan",
   "hand": "",
   "positions": []
  },
  "desc": "Cargo-area liner moulded for the Hyundai Elantra sedan, cut at 3.5 mm thickness to cover the boot floor in a full set. Raised edges keep shopping, tools and wet outdoor gear contained, so the boot trim and carpet stay free of stains. The TPE sheet is odourless and plasticiser-free, halogen-free and recyclable, and stays flexible in cold weather, which matters when a stiff liner has to be lifted out. It is waterproof, so it wipes or rinses clean. Buyers should confirm the body style and model year. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Hyundai Elantra Sedan 3.5mm - confirm year with us"
   ],
   [
    "Coverage",
    "Cargo-area coverage, raised lip"
   ],
   [
    "Thickness",
    "3.5 mm"
   ],
   [
    "Body type",
    "Sedan"
   ],
   [
    "MOQ",
    "1 set"
   ]
  ],
  "points": [
   "Cargo liner for the Elantra sedan boot floor",
   "3.5mm sheet with raised containment edges",
   "Wipes or rinses clean after use",
   "Confirm body style and model year"
  ],
  "related": [
   "buick-trunk-mats",
   "tesla-cybertruck-trunk-mats"
  ]
 },
 {
  "slug": "mazda-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Mazda - Made to Order",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/mazda-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/OEM-Molded-5D-TPE-Car-Floor_1601951221109.html",
  "fitment": {},
  "desc": "Five-dimensional TPE floor liner made to order for your Mazda model, with a moulded tray that wraps the footwell and edges up to the trim. The wear-resistant surface handles daily use, and the liner is built to be easy to clean: lift it out, shake it, rinse it. Sets are supplied in three pieces. TPE is odourless because no plasticiser is used, halogen-free and recyclable, and it keeps its flexibility in cold weather so it does not crack when emptied. Because fitment is produced to order, buyers should confirm model and year. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Mazda - model and year on request"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Mazda3"
   ]
  ],
  "points": [
   "Made to order for your Mazda model",
   "Wear-resistant surface for daily driving",
   "Lifts out and rinses between washes",
   "Single-set minimum for a first order"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "mazda-floor-liners-2",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Mazda - Made to Order - or TOYOTA RAV",
  "badge": "3D Fit",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/mazda-floor-liners-2.jpg",
  "src": "https://www.alibaba.com/product-detail/Odorless-Virgin-TPE-3D-Car-Mats_1601867045669.html",
  "fitment": {},
  "desc": "Three-dimensional TPE floor mat made to order for your Mazda model. The liner is moulded rather than trimmed, so the outline follows the footwell and the raised sides sit against the trim. The TPE grade used here is virgin material, odourless because no plasticiser is added, and it is halogen-free and recyclable, staying flexible in cold weather. Water and dust are held on the surface and lift away with a rinse, so the carpet underneath stays clean. Sets are supplied in three pieces. Send the model and year with your enquiry. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Mazda - model and year on request"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "or TOYOTA RAV"
   ]
  ],
  "points": [
   "Made to order for your Mazda model",
   "Virgin TPE grade, odourless, no plasticiser",
   "Three-piece set with a moulded outline",
   "Single-set minimum to trial the fit"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "mercedes-benz-c260l-w205-w206-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Mercedes-Benz C260L / W205 / W206",
  "badge": "Custom Fit",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/mercedes-benz-c260l-w205-w206-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Exclusive-Mold-Floor-Mats-Fit_1601867072689.html",
  "fitment": {
   "make": "Mercedes-Benz",
   "model": "C260L / W205 / W206",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Floor liner moulded from an exclusive pattern for the Mercedes-Benz C260L W205 and W206, giving full surround coverage of the footwell. The moulded walls rise to meet the console and sill trim, so water and grit are held away from the carpet edge. Three pieces cover the front and rear. The TPE compound is odourless, carries no plasticiser, and is halogen-free and recyclable; it remains flexible in cold weather. Cleaning is straightforward: lift the liner, tip it out, rinse if needed. Confirm the body code and model year when ordering. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Mercedes-Benz C260L / W205 / W206 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Mercedes-Benz C260L"
   ]
  ],
  "points": [
   "Exclusive pattern for C260L W205 and W206",
   "Full surround coverage up to the trim",
   "Anti-slip base, easy to lift and rinse",
   "Confirm body code and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "mercedes-benz-e300l-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Mercedes-Benz E300L",
  "badge": "All-Season",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/mercedes-benz-e300l-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-3D-Laser-Scan-TPE-Floor_1601865921073.html",
  "fitment": {
   "make": "Mercedes-Benz",
   "model": "E300L",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "TPE floor mat for the Mercedes-Benz E300L, cut from a laser-scanned pattern so the outline follows the footwell accurately. A deep channel runs along each mat to hold water, snow melt and grit below the surrounding surface, and the non-slip backing keeps the mat from shifting. Three pieces cover the front and rear. The material is odourless, free of plasticiser, halogen-free and recyclable, and stays flexible in cold weather. Wear resistance suits daily use, and cleaning is a rinse. Confirm the model year at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Mercedes-Benz E300L - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "r Benz E300"
   ]
  ],
  "points": [
   "Laser-scanned pattern for the Mercedes-Benz E300L",
   "Deep channel holds meltwater and grit",
   "Non-slip backing keeps the mat in place",
   "Confirm model year when ordering"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "nissan-navara-np300-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Nissan Navara NP300",
  "badge": "Low MOQ",
  "price": "$18-20/set",
  "moq": "MOQ 10 sets",
  "img": "/images/nissan-navara-np300-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Fit-TPE-Floor-Mats-For_1601928713995.html",
  "fitment": {
   "make": "Nissan",
   "model": "Navara NP300",
   "years": "",
   "body": "Pickup",
   "hand": "",
   "positions": []
  },
  "desc": "Moulded floor liner for the Nissan Navara NP300 pickup, shaped as a 3D tray with raised edges for a vehicle that sees muck, gravel and wet kit. The moulding follows the footwell so it sits flat and does not creep under the pedals. Three or five pieces cover the rows as required. TPE has no plasticiser, so the set is odourless, and it is halogen-free, recyclable and stays flexible in cold conditions. Being waterproof, it can be lifted out and hosed. Model year is not fixed in this listing, so confirm it before ordering. Ten sets minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Nissan Navara NP300 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Body type",
    "Pickup"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W Nissan"
   ]
  ],
  "points": [
   "Moulded for the Navara NP300 pickup",
   "Sits flat in the footwell, clear of the pedals",
   "Odourless, plasticiser-free TPE",
   "Ten-set minimum for distributor orders"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "nissan-x-trail-snow-mud-proof-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Nissan X-Trail Snow Mud Proof",
  "badge": "OEM Ready",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/nissan-x-trail-snow-mud-proof-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Durable-3D-5D-Full-Coverage-TPE_1601873127252.html",
  "fitment": {
   "make": "Nissan",
   "model": "X-Trail Snow Mud Proof",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Durable TPE floor liner moulded for the Nissan X-Trail, with full-coverage 3D and 5D walls and a surface that stands up to snow, mud and grit carried in on boots. The liner is built to be rinsed: a hose and a wipe clears most of the mess, and the material does not absorb water. TPE is odourless, free of plasticiser, halogen-free and recyclable, and stays flexible in cold conditions. Three pieces cover the front and rear. Buyers should confirm model and year before the order is placed. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Nissan X-Trail Snow Mud Proof - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Nissan X-Trail"
   ]
  ],
  "points": [
   "Made for the Nissan X-Trail footwell",
   "Snow, mud and grit rinse off easily",
   "Flexible, odourless, recyclable TPE",
   "Confirm model and year at ordering"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "tesla-cybertruck-trunk-mats",
  "cat": "trunk-mats",
  "name": "TPE Cargo Liner for Tesla Cybertruck 2024-2026",
  "badge": "3D Fit",
  "price": "$14-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/tesla-cybertruck-trunk-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/TPE-Rear-Cargo-Liner-Custom-Fit_1601874920736.html",
  "fitment": {
   "make": "Tesla",
   "model": "Cybertruck",
   "years": "2024-2026",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Rear cargo liner moulded for the Tesla Cybertruck over 2024-2026, in left-hand drive. The liner covers the trunk floor in TPE with an anti-slip face and raised edges, so tools, wet gear and loose loads stay contained and the original floor surface is protected. The material is waterproof and odourless, with no plasticiser, and it is halogen-free and recyclable; it also stays flexible in cold weather. Lifting it out and rinsing it clears mud or spills quickly, and the TPE surface drains without holding moisture. Three pieces are included in the set. FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Tesla Cybertruck (2024-2026)"
   ],
   [
    "Coverage",
    "Cargo-area coverage, raised lip"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Tesla Cybertruck"
   ]
  ],
  "points": [
   "Moulded for Cybertruck 2024-2026, left-hand drive",
   "Anti-slip cargo face holds loose loads",
   "Waterproof, odourless, recyclable TPE",
   "Lifts out for a quick rinse"
  ],
  "related": [
   "buick-trunk-mats",
   "hyundai-elantra-sedan-3-5mm-trunk-mats"
  ]
 },
 {
  "slug": "toyota-corolla-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Corolla",
  "badge": "Custom Fit",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-corolla-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-wholesale-TPE-3D-5D-car_1601870379210.html",
  "fitment": {
   "make": "Toyota",
   "model": "Corolla",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Three-dimensional and five-dimensional TPE floor mat made for the Toyota Corolla, with a moulded outline that follows the footwell and raised sides that keep water and grit contained. The flexible TPE compound is odourless, plasticiser-free, halogen-free and recyclable, and stays supple when the weather turns cold, so the liner can be lifted and emptied without cracking. The TPE sheet is specified at 3.5 mm thickness. Cleaning takes a rinse and a wipe. Three pieces cover the front and rear. Confirm the Corolla generation and model year when ordering. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Corolla - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Toyota corolla"
   ]
  ],
  "points": [
   "Made for the Toyota Corolla footwell",
   "Flexible in cold with no plasticiser odour",
   "Lift out and rinse to clean",
   "Confirm generation and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-corolla-floor-liners-2",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Corolla - W-68 for Toyota",
  "badge": "All-Season",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-corolla-floor-liners-2.jpg",
  "src": "https://www.alibaba.com/product-detail/All-Weather-Heavy-Duty-Raised-Edge_1601932257470.html",
  "fitment": {
   "make": "Toyota",
   "model": "Corolla",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Heavy-duty all-weather TPE liner moulded for the Toyota Corolla on tool W-68, with a raised edge that keeps dust, mud and snow melt inside the tray. The wear-resistant surface is made for daily driving and the liner is waterproof, so cleaning is a rinse rather than a scrub. Sets are supplied in three or five pieces. TPE is odourless, uses no plasticiser, is halogen-free and recyclable, and stays flexible in cold weather. Buyers should confirm the model generation and year, as no production range is fixed here. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Corolla - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W-68 Toyota"
   ]
  ],
  "points": [
   "Tooled on W-68 for the Toyota Corolla",
   "Raised edge blocks dust, mud and snow melt",
   "Wear-resistant, waterproof surface",
   "Confirm generation and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-crown-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Crown",
  "badge": "Low MOQ",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-crown-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-Direct-LHD-3D-5D-TPE_1601886937751.html",
  "fitment": {
   "make": "Toyota",
   "model": "Crown",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Three-dimensional and five-dimensional TPE floor liner for the Toyota Crown in left-hand drive, moulded to the footwell with raised walls that hold water and grit inside the tray. Sets are supplied in three or five pieces. The material is odourless, carries no plasticiser, is halogen-free and recyclable, and stays flexible in cold weather. Waterproof construction means the liner rinses clean. Buyers should confirm the model and year, as the listing does not fix a range. Bulk quantities suit wholesale buyers, one set minimum applies, and FOB pricing is on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Crown - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Toyota Crown"
   ]
  ],
  "points": [
   "Left-hand-drive liner for the Toyota Crown",
   "Three-piece or five-piece set options",
   "Logo printing available for buyer labels",
   "Bulk quantities for wholesale programmes"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-fortuner-prado-raised-edge-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Fortuner Prado Raised Edge",
  "badge": "OEM Ready",
  "price": "$22-24/set",
  "moq": "MOQ 10 sets",
  "img": "/images/toyota-fortuner-prado-raised-edge-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/5D-Eco-TPE-Car-Mats-Custom_1601878932692.html",
  "fitment": {
   "make": "Toyota",
   "model": "Fortuner Prado Raised Edge",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Five-dimensional TPE liner moulded for the Toyota Fortuner and Prado, with a raised edge that runs around the whole tray and stands well above the carpet. That edge is what keeps mud and standing water in place on the liner instead of spreading across the footwell. Three pieces cover the front and rear. The material is odourless, free of plasticiser, halogen-free and recyclable, and remains flexible in cold weather. Marks lift off easily with a rinse because the surface is waterproof. Model and year should be confirmed at order stage. Ten sets minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Fortuner Prado Raised Edge - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W TOYOTA"
   ]
  ],
  "points": [
   "Raised edge runs around the whole tray",
   "Moulded for Toyota Fortuner and Prado",
   "Waterproof TPE rinses clean",
   "Confirm model and year before tooling"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-hilux-revo-2015-2025-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Hilux Revo 2015-2025 2015-2025",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 10 sets",
  "img": "/images/toyota-hilux-revo-2015-2025-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-TPE-Car-Floor-Mats-for_1601926331668.html",
  "fitment": {
   "make": "Toyota",
   "model": "Hilux Revo 2015-2025",
   "years": "2015-2025",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Three-dimensional floor liner moulded for the Toyota Hilux Revo over 2015-2025, in left-hand drive. High side walls and a deep channel form a tray that holds mud, water and farm grit below the level of the carpet, which matters on a working pickup. Available in 3-piece and 5-piece sets. The TPE shell is odourless, without plasticiser, halogen-free and recyclable, and does not stiffen in cold weather. Cleaning is a lift-out and a rinse. Longer production runs are handled in-house from the W-54 tooling, so repeat orders keep the same shape. Ten sets minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Hilux Revo 2015-2025 (2015-2025)"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "10 sets"
   ],
   [
    "Tooling / model no.",
    "W-54 TOYOTA"
   ]
  ],
  "points": [
   "Moulded for Hilux Revo 2015-2025, left-hand drive",
   "Deep channel contains mud and standing water",
   "Choice of 3-piece or 5-piece sets",
   "Repeat orders keep the same tool form"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-hilux-vigo-dual-cab-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Hilux Vigo Dual Cab",
  "badge": "Custom Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-hilux-vigo-dual-cab-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-Custom-5D-TPE-Car-Foot_1601926373346.html",
  "fitment": {
   "make": "Toyota",
   "model": "Hilux Vigo Dual Cab",
   "years": "",
   "body": "",
   "hand": "LHD",
   "positions": []
  },
  "desc": "Five-dimensional TPE floor mat moulded for the Toyota Hilux Vigo in dual cab form and left-hand drive, produced on tool W-46. The liner follows the footwell of the cab closely and the raised edge contains mud, water and gravel brought in from site work. Sets come in three or five pieces. TPE is odourless and plasticiser-free, halogen-free and recyclable, and does not harden in cold weather. Cleaning is simply a lift-out and a rinse. Buyers should confirm the cab configuration, drive side and model year. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Hilux Vigo Dual Cab - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Drive side",
    "LHD"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W-46 TOYOTA"
   ]
  ],
  "points": [
   "Dual cab, left-hand-drive tooling W-46",
   "Moulded for the Toyota Hilux Vigo",
   "Raised edge contains site mud and gravel",
   "Confirm cab layout and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-land-cruiser-lc200-lc300-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Land Cruiser LC200 LC300",
  "badge": "All-Season",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-land-cruiser-lc200-lc300-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-TPE-Car-Floor-Mats-for_1601928823147.html",
  "fitment": {
   "make": "Toyota",
   "model": "Land Cruiser LC200 LC300",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Moulded floor liner for the Toyota Land Cruiser LC200 and LC300, produced on tool W-32. The 3D tray hugs the footwell with raised edges so mud, grit and water stay contained on rough roads and building sites. Three pieces cover the front and rear footwells. TPE is odourless, uses no plasticiser, stays pliable in cold, and is halogen-free and recyclable; the surface is waterproof and the backing anti-slip. Cleaning takes a rinse and a wipe. The listing does not fix a year range, so buyers should confirm their model year before the order is placed. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Land Cruiser LC200 LC300 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W-32 TOYOTA"
   ]
  ],
  "points": [
   "Tooled for Land Cruiser LC200 and LC300",
   "Raised edges hold mud and water",
   "Waterproof surface with anti-slip backing",
   "Confirm model year when ordering"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-land-cruiser-prado-lc150-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota Land Cruiser Prado LC150",
  "badge": "Low MOQ",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-land-cruiser-prado-lc150-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Custom-Molded-TPE-Car-Floor-Liners_1601948650259.html",
  "fitment": {
   "make": "Toyota",
   "model": "Land Cruiser Prado LC150",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Moulded TPE floor liner for the Toyota Land Cruiser Prado LC150, with a durable profile intended for wear in a heavy vehicle. The tray has raised edges and covers the footwell closely, so grit and water are held in the liner rather than ground into the carpet. Three pieces cover the front and rear rows. TPE is odourless, plasticiser-free, halogen-free and recyclable, and stays flexible when cold. Cleaning is a lift-out and a rinse. Because the listing does not fix a model year, buyers should confirm theirs at order stage. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota Land Cruiser Prado LC150 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Toyota"
   ]
  ],
  "points": [
   "Made for the Land Cruiser Prado LC150",
   "Raised edges hold grit and water",
   "Plasticiser-free TPE stays flexible in cold",
   "Confirm model year at order stage"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-rav4-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota RAV4",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-rav4-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-TPE-Car-Floor-Mats-Custom_1601884906517.html",
  "fitment": {
   "make": "Toyota",
   "model": "RAV4",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "All-weather TPE floor liner custom fit for the Toyota RAV4, with a moulded tray outline and high side walls that follow the footwell and reduce gaps at the console. Water, mud and grit stay on the liner through wet seasons. Sets are supplied in three or five pieces. The TPE compound is odourless, free of plasticiser, halogen-free and recyclable, and remains flexible in cold weather, so the liner can be emptied without stiffening. Cleaning is a lift-out and a rinse. Confirm model and year when ordering. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota RAV4 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Toyota RAV4"
   ]
  ],
  "points": [
   "Custom fit for the Toyota RAV4 footwell",
   "High side walls reduce gaps at the console",
   "Odourless, halogen-free, recyclable TPE",
   "Three-piece or five-piece set options"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "toyota-prius-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Toyota prius",
  "badge": "3D Fit",
  "price": "$17-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/toyota-prius-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Heavy-Duty-3D-5D-Full-Coverage_1601873028946.html",
  "fitment": {
   "make": "Toyota",
   "model": "prius",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Heavy-duty TPE floor liner moulded for the Toyota Prius, formed as a 3D and 5D full-coverage tray with high walls along the footwell. The anti-stain surface keeps ground-in mud and spilled coffee from marking the liner, so it stays presentable between washes. Three pieces cover the front and rear. The TPE compound is odourless, uses no plasticiser, is halogen-free and recyclable, and stays flexible in cold weather. Cleaning is a lift, a rinse and a wipe. Buyers should confirm the model generation and year, since the listing does not fix one. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Toyota prius - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "For toyota prius"
   ]
  ],
  "points": [
   "Moulded for the Toyota Prius footwell",
   "Anti-stain surface resists ground-in mud",
   "Waterproof TPE lifts, rinses and wipes",
   "Confirm generation and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "volkswagen-polo-mk5-mk8-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Volkswagen Polo Mk5-Mk8",
  "badge": "Custom Fit",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/volkswagen-polo-mk5-mk8-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Eco-Odor-Free-TPE-Liners-for_1601868773808.html",
  "fitment": {
   "make": "Volkswagen",
   "model": "Polo Mk5-Mk8",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Floor liner moulded for the Volkswagen Polo Mk5 through Mk8, with a deep dish under each footwell designed to stop water overflowing onto the carpet when the liner is full. The dish and raised perimeter work together for snow, slush and spilled drinks. Three pieces cover the front and rear. The TPE shell is odourless, without plasticiser, halogen-free and recyclable, and keeps its flexibility in cold weather so it can be emptied without cracking. Cleaning means lifting the liner out and rinsing the dish. Buyers should confirm the Polo mark and model year. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Volkswagen Polo Mk5-Mk8 - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Volkswagen polo"
   ]
  ],
  "points": [
   "Deep dish stops water overflowing the liner",
   "Moulded for Volkswagen Polo Mk5 to Mk8",
   "Empty and rinse without cracking in cold",
   "Confirm mark and model year"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "wuling-bingo-floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners for Wuling Bingo",
  "badge": "All-Season",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/wuling-bingo-floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Wuling-Bingo-Special-TPE-3D-5D_1601870309426.html",
  "fitment": {
   "make": "Wuling",
   "model": "Bingo",
   "years": "",
   "body": "",
   "hand": "",
   "positions": []
  },
  "desc": "Three-dimensional and five-dimensional TPE floor liner made for the Wuling Bingo, with a moulded outline that follows the footwell of the compact model instead of sitting flat over the carpet. Raised edges contain water and grit, and the waterproof surface wipes clean after a rinse. Three pieces cover the front and rear. TPE carries no plasticiser, so the set is odourless, and it is halogen-free and recyclable, staying flexible in cold weather. Confirm the model and year at order stage, as the listing does not fix a production range. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Wuling Bingo - confirm year with us"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "TPE Car Mats"
   ]
  ],
  "points": [
   "Moulded for the Wuling Bingo footwell",
   "Raised edges contain water and grit",
   "Flexible, odourless, recyclable TPE",
   "Confirm model and year before tooling"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners",
  "cat": "floor-liners",
  "name": "TPE Floor Liners - Made to Order",
  "badge": "Low MOQ",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners.jpg",
  "src": "https://www.alibaba.com/product-detail/Factory-TPE-Car-Floor-Liner-For_1601928677938.html",
  "fitment": {},
  "desc": "Three-dimensional TPE floor liner made to order for your model, with the tray moulded to the footwell rather than trimmed from a flat sheet. High side walls contain mud, water and grit, which keeps the original carpet clean in daily use. Sets are supplied in three pieces covering driver, passenger and rear. The material is odourless because no plasticiser is used, stays flexible in low temperatures, and is halogen-free and recyclable. It is waterproof and wipes clean after a rinse. Because this listing carries no fixed model data, buyers send the vehicle model and year and we produce tooling to suit. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "W-32 TOYOTA"
   ]
  ],
  "points": [
   "Made to order for your specific model",
   "High side walls keep grit off the carpet",
   "Three-piece set covers driver and rear",
   "Odourless, halogen-free, recyclable TPE"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners-2",
  "cat": "floor-liners",
  "name": "TPE Floor Liners - Made to Order - Tesla model y juniper",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners-2.jpg",
  "src": "https://www.alibaba.com/product-detail/High-Quality-Car-Carpet-Foot-Mat_1601857282620.html",
  "fitment": {},
  "desc": "Waterproof TPE floor liner made to order for your model, finished with a non-slip surface and a moulded tray profile. The liner is produced from tooling cut for the vehicle you specify, so it follows the footwell instead of sitting on top of it. Sets are available in three or five pieces. TPE is odourless because it contains no plasticiser, is halogen-free and recyclable, and stays flexible in cold weather. Water and grit stay on the surface and lift away with a rinse, which keeps the original carpet clean through winter. Send the model and year with your enquiry. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Tesla model y juniper"
   ]
  ],
  "points": [
   "Made to order for your specified model",
   "Non-slip, waterproof surface",
   "Three-piece or five-piece sets",
   "Odourless, halogen-free, recyclable TPE"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners-3",
  "cat": "floor-liners",
  "name": "Custom Printed Thickened TPE Floor Liners - Made to Order",
  "badge": "3D Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners-3.jpg",
  "src": "https://www.alibaba.com/product-detail/Thickened-Rubber-Car-Floor-Carpets-With_1601879977038.html",
  "fitment": {},
  "desc": "Full-set floor liner made to order for your model, produced in a thickened sheet with a custom printed pattern across the surface. The set is supplied in three or five pieces and the printed face is non-slip underfoot. TPE of this build is odourless because no plasticiser is added, is halogen-free and recyclable, and stays flexible in cold conditions so the liner can be rolled or lifted without cracking. The material is waterproof and wipes clean after a rinse. Send your model and year so the pattern and outline can be made to suit. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Leather Car Mats"
   ]
  ],
  "points": [
   "Made to order to your model and year",
   "Thickened sheet with custom printed pattern",
   "Non-slip face, three or five pieces",
   "Waterproof and odourless TPE build"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "double-layer-mats",
  "cat": "double-layer-mats",
  "name": "Double-Layer Double-Layer TPE Car Mats - Made to Order",
  "badge": "Custom Fit",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/double-layer-mats.jpg",
  "src": "https://www.alibaba.com/product-detail/Wholesale-Dual-Layer-TPE-Car-Floor_1601950975426.html",
  "fitment": {},
  "desc": "Double-layer floor mat made to order for your model, with a detachable upper layer that lifts out of the base tray. The top layer can be removed for cleaning while the moulded base stays in the footwell, which shortens turnaround between washes. Sets are supplied in three pieces. Both layers are TPE, odourless and plasticiser-free, halogen-free and recyclable, and remain flexible in cold weather. The base is waterproof, so spills stay in the tray rather than soaking the carpet. Send your model and year so the base can be tooled. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "Detachable two-layer construction"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Mazda3"
   ]
  ],
  "points": [
   "Detachable top layer lifts out for cleaning",
   "Moulded base tray stays in the footwell",
   "Both layers odourless, recyclable TPE",
   "Made to order for your model"
  ],
  "related": []
 },
 {
  "slug": "floor-liners-4",
  "cat": "floor-liners",
  "name": "10 mm Thick Thickened TPE Floor Liners - Made to Order",
  "badge": "All-Season",
  "price": "$15-23/piece",
  "moq": "MOQ 1 piece",
  "img": "/images/floor-liners-4.jpg",
  "src": "https://www.alibaba.com/product-detail/All-Weather-Waterproof-10mm-Thick-2_1601925437728.html",
  "fitment": {},
  "desc": "All-weather TPE floor liner made to order for your model, produced in a 10 mm thickness for heavier coverage and supplied as a two-piece set. The thicker sheet stands up to daily wear and holds its shape in the footwell, while the waterproof surface keeps water and grit off the carpet. TPE at this build is odourless and plasticiser-free, halogen-free and recyclable, and stays flexible in cold weather. Cleaning is a rinse and a wipe. Because this listing carries no fixed model data, buyers send the model and year with the enquiry. Units are quoted per piece, priced FOB on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Thickness",
    "10 mm"
   ],
   [
    "MOQ",
    "1 piece"
   ]
  ],
  "points": [
   "10mm thickness for heavier wear",
   "Two-piece set, quoted per piece",
   "Made to order for your model",
   "Waterproof TPE rinses clean"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners-5",
  "cat": "floor-liners",
  "name": "TPE Floor Liners - Made to Order - Leather Car Mats",
  "badge": "Low MOQ",
  "price": "$20-23/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners-5.jpg",
  "src": "https://www.alibaba.com/product-detail/3D-5D-Custom-Mold-TPE-Floor_1601865763098.html",
  "fitment": {},
  "desc": "Custom-moulded TPE floor liner made to order for your model, formed as a 3D and 5D tray with deep surrounding walls rather than a flat mat. The moulded walls hold water, mud and grit inside the liner and away from the carpet and trim. Sets are supplied in three pieces. The TPE compound is odourless and carries no plasticiser, is halogen-free and recyclable, and remains flexible when temperatures drop. Being waterproof, the liner can be lifted out and rinsed clean. Because the listing fixes no model, buyers send the model and year so tooling can be prepared. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Leather Car Mats"
   ]
  ],
  "points": [
   "Deep surround walls made to your model",
   "Three-piece TPE set",
   "Waterproof and easy to rinse out",
   "Odourless, halogen-free, recyclable"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners-6",
  "cat": "floor-liners",
  "name": "Custom Printed 5-Piece TPE Floor Liners - Made to Order",
  "badge": "OEM Ready",
  "price": "$18-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners-6.jpg",
  "src": "https://www.alibaba.com/product-detail/Anti-Slip-Custom-Printed-Rubber-Foot_1601879623299.html",
  "fitment": {},
  "desc": "Custom-printed floor mat made to order for your vehicle model, supplied as a full set in three or five pieces. The printed surface is treated to be anti-slip underfoot, and the material is a TPE rubber that is odourless because it holds no plasticiser. It is halogen-free and recyclable, and it stays flexible in cold weather, so the mats lie flat in the footwell instead of curling. Water and dirt do not soak in, so cleaning is a shake-out and a rinse. Send the model and year with the enquiry so the print and outline can be matched. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "Handa"
   ]
  ],
  "points": [
   "Custom printed mat set for your model",
   "Anti-slip printed face",
   "Lies flat and resists curling in cold",
   "Three-piece or five-piece sets"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 },
 {
  "slug": "floor-liners-7",
  "cat": "floor-liners",
  "name": "TPE Floor Liners - Made to Order - TPE Car Mats",
  "badge": "3D Fit",
  "price": "$16-20/set",
  "moq": "MOQ 1 set",
  "img": "/images/floor-liners-7.jpg",
  "src": "https://www.alibaba.com/product-detail/Full-Surround-TPE-Auto-Mats-Designed_1601868951315.html",
  "fitment": {},
  "desc": "Full-surround TPE mat made to order for a daily-commute sedan, with moulded walls that cover the footwell up to the trim. The anti-stain surface keeps grit and spilled drinks from marking the liner, and the non-slip backing holds it in place underfoot. Sets are supplied in three pieces. TPE is odourless because no plasticiser is used, and it is halogen-free and recyclable, staying flexible in cold weather. Waterproof construction means the mat can be lifted out and rinsed. Send the model and year with the enquiry. One set minimum, FOB pricing on request.",
  "specs": [
   [
    "Material",
    "TPE (Thermoplastic Elastomer), odourless"
   ],
   [
    "Fitment",
    "Made to order - send us your model and year"
   ],
   [
    "Coverage",
    "3D full coverage, high side walls"
   ],
   [
    "Body type",
    "Sedan"
   ],
   [
    "MOQ",
    "1 set"
   ],
   [
    "Tooling / model no.",
    "TPE Car Mats"
   ]
  ],
  "points": [
   "Full surround for a daily-commute sedan",
   "Anti-stain surface with non-slip backing",
   "Made to order for your model",
   "Three-piece set, single-set minimum"
  ],
  "related": [
   "audi-a6-a8-floor-liners",
   "byd-seagull-atto-1-ev-floor-liners",
   "buick-floor-liners"
  ]
 }
]

# ---------------------------------------------------------------------------
# VEHICLES (37) - built from listing titles only
# ---------------------------------------------------------------------------
VEHICLES = [
 {
  "make": "Audi",
  "model": "A6 A8",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "audi-a6-a8-floor-liners"
  ],
  "slug": "audi-a6-a8"
 },
 {
  "make": "BYD",
  "model": "Atto",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "byd-atto-all-weather-mats"
  ],
  "slug": "byd-atto"
 },
 {
  "make": "BYD",
  "model": "Dolphin Seal Atto3",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "byd-dolphin-seal-atto3-all-weather-mats"
  ],
  "slug": "byd-dolphin-seal-atto3"
 },
 {
  "make": "BYD",
  "model": "Seagull Atto 1 EV",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "byd-seagull-atto-1-ev-floor-liners"
  ],
  "slug": "byd-seagull-atto-1-ev"
 },
 {
  "make": "BYD",
  "model": "Song Plus DM-i Seal",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "byd-song-plus-dm-i-seal-all-weather-mats"
  ],
  "slug": "byd-song-plus-dm-i-seal"
 },
 {
  "make": "Buick",
  "model": "Excelle",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "buick-excelle-floor-liners"
  ],
  "slug": "buick-excelle"
 },
 {
  "make": "Changan",
  "model": "CS75 PLUS MK4",
  "years": "",
  "body": "Suv",
  "hand": "LHD",
  "products": [
   "changan-cs75-plus-mk4-floor-liners"
  ],
  "slug": "changan-cs75-plus-mk4"
 },
 {
  "make": "Changan",
  "model": "UNI-T 2023-2026",
  "years": "2023-2026",
  "body": "",
  "hand": "LHD",
  "products": [
   "changan-uni-t-2023-2026-floor-liners"
  ],
  "slug": "changan-uni-t-2023-2026"
 },
 {
  "make": "Chery",
  "model": "Fulwin T9L",
  "years": "",
  "body": "Suv",
  "hand": "",
  "products": [
   "chery-fulwin-t9l-floor-liners"
  ],
  "slug": "chery-fulwin-t9l"
 },
 {
  "make": "Chery",
  "model": "Tiggo",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "chery-tiggo-floor-liners"
  ],
  "slug": "chery-tiggo"
 },
 {
  "make": "Fiat",
  "model": "Palio",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "fiat-palio-floor-liners"
  ],
  "slug": "fiat-palio"
 },
 {
  "make": "Ford",
  "model": "F150 Raptor",
  "years": "",
  "body": "Pickup",
  "hand": "",
  "products": [
   "ford-f150-raptor-floor-liners"
  ],
  "slug": "ford-f150-raptor"
 },
 {
  "make": "Ford",
  "model": "Ranger Escape Mustang",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "ford-ranger-escape-mustang-floor-liners"
  ],
  "slug": "ford-ranger-escape-mustang"
 },
 {
  "make": "Ford",
  "model": "Ranger Raptor",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "ford-ranger-raptor-all-weather-mats"
  ],
  "slug": "ford-ranger-raptor"
 },
 {
  "make": "Ford",
  "model": "Territory Destroyer 2019-2023",
  "years": "2019-2023",
  "body": "",
  "hand": "",
  "products": [
   "ford-territory-destroyer-2019-2023-floor-liners"
  ],
  "slug": "ford-territory-destroyer-2019-2023"
 },
 {
  "make": "Geely",
  "model": "EX2 Xingyuan EV",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "geely-ex2-xingyuan-ev-floor-liners"
  ],
  "slug": "geely-ex2-xingyuan-ev"
 },
 {
  "make": "Geely",
  "model": "Panda Mini EV",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "geely-panda-mini-ev-floor-liners"
  ],
  "slug": "geely-panda-mini-ev"
 },
 {
  "make": "Geely",
  "model": "Xingyuan EX2 EV",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "geely-xingyuan-ex2-ev-floor-liners"
  ],
  "slug": "geely-xingyuan-ex2-ev"
 },
 {
  "make": "Honda",
  "model": "CR-V",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "honda-cr-v-floor-liners"
  ],
  "slug": "honda-cr-v"
 },
 {
  "make": "Hongqi",
  "model": "H5 / H6 / H7 / H9",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "hongqi-h5-h6-h7-h9-floor-liners"
  ],
  "slug": "hongqi-h5-h6-h7-h9"
 },
 {
  "make": "Hyundai",
  "model": "Elantra Sedan 3.5mm",
  "years": "",
  "body": "Sedan",
  "hand": "",
  "products": [
   "hyundai-elantra-sedan-3-5mm-trunk-mats"
  ],
  "slug": "hyundai-elantra-sedan-3-5mm"
 },
 {
  "make": "Mercedes-Benz",
  "model": "C260L / W205 / W206",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "mercedes-benz-c260l-w205-w206-floor-liners"
  ],
  "slug": "mercedes-benz-c260l-w205-w206"
 },
 {
  "make": "Mercedes-Benz",
  "model": "E300L",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "mercedes-benz-e300l-floor-liners"
  ],
  "slug": "mercedes-benz-e300l"
 },
 {
  "make": "Nissan",
  "model": "Navara NP300",
  "years": "",
  "body": "Pickup",
  "hand": "",
  "products": [
   "nissan-navara-np300-floor-liners"
  ],
  "slug": "nissan-navara-np300"
 },
 {
  "make": "Nissan",
  "model": "X-Trail Snow Mud Proof",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "nissan-x-trail-snow-mud-proof-floor-liners"
  ],
  "slug": "nissan-x-trail-snow-mud-proof"
 },
 {
  "make": "Tesla",
  "model": "Cybertruck",
  "years": "2024-2026",
  "body": "",
  "hand": "LHD",
  "products": [
   "tesla-cybertruck-trunk-mats"
  ],
  "slug": "tesla-cybertruck"
 },
 {
  "make": "Toyota",
  "model": "Corolla",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-corolla-floor-liners",
   "toyota-corolla-floor-liners-2"
  ],
  "slug": "toyota-corolla"
 },
 {
  "make": "Toyota",
  "model": "Crown",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "toyota-crown-floor-liners"
  ],
  "slug": "toyota-crown"
 },
 {
  "make": "Toyota",
  "model": "Fortuner Prado Raised Edge",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-fortuner-prado-raised-edge-floor-liners"
  ],
  "slug": "toyota-fortuner-prado-raised-edge"
 },
 {
  "make": "Toyota",
  "model": "Hilux Revo 2015-2025",
  "years": "2015-2025",
  "body": "",
  "hand": "LHD",
  "products": [
   "toyota-hilux-revo-2015-2025-floor-liners"
  ],
  "slug": "toyota-hilux-revo-2015-2025"
 },
 {
  "make": "Toyota",
  "model": "Hilux Vigo Dual Cab",
  "years": "",
  "body": "",
  "hand": "LHD",
  "products": [
   "toyota-hilux-vigo-dual-cab-floor-liners"
  ],
  "slug": "toyota-hilux-vigo-dual-cab"
 },
 {
  "make": "Toyota",
  "model": "Land Cruiser LC200 LC300",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-land-cruiser-lc200-lc300-floor-liners"
  ],
  "slug": "toyota-land-cruiser-lc200-lc300"
 },
 {
  "make": "Toyota",
  "model": "Land Cruiser Prado LC150",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-land-cruiser-prado-lc150-floor-liners"
  ],
  "slug": "toyota-land-cruiser-prado-lc150"
 },
 {
  "make": "Toyota",
  "model": "RAV4",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-rav4-floor-liners"
  ],
  "slug": "toyota-rav4"
 },
 {
  "make": "Toyota",
  "model": "prius",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "toyota-prius-floor-liners"
  ],
  "slug": "toyota-prius"
 },
 {
  "make": "Volkswagen",
  "model": "Polo Mk5-Mk8",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "volkswagen-polo-mk5-mk8-floor-liners"
  ],
  "slug": "volkswagen-polo-mk5-mk8"
 },
 {
  "make": "Wuling",
  "model": "Bingo",
  "years": "",
  "body": "",
  "hand": "",
  "products": [
   "wuling-bingo-floor-liners"
  ],
  "slug": "wuling-bingo"
 }
]


# ---------------------------------------------------------------------------
# derived lookups - do not edit by hand
# ---------------------------------------------------------------------------
RELATED_INDEX = {p["slug"]: p for p in PRODUCTS}
VEHICLE_INDEX = {v["slug"]: v for v in VEHICLES}


def _norm(x):
    return " ".join(str(x or "").strip().lower().split())


def products_for_vehicle(v):
    wanted = set(v.get("products") or [])
    if wanted:
        found = [p for p in PRODUCTS if p["slug"] in wanted]
        if found:
            return found
    out = []
    for p in PRODUCTS:
        f = p.get("fitment") or {}
        if _norm(f.get("make")) == _norm(v.get("make")) and _norm(f.get("model")) == _norm(v.get("model")):
            out.append(p)
    return out


def vehicles_for_product(p):
    f = p.get("fitment") or {}
    return [v for v in VEHICLES
            if _norm(v.get("make")) == _norm(f.get("make")) and _norm(v.get("model")) == _norm(f.get("model"))]


def category_name(cid):
    for c in CATEGORIES:
        if c["id"] == cid:
            return c["name"]
    return cid
